
const number = 4;

//number = 2;

try{
    number = 2;
}catch(err){
    console.log("err : "+err);
}
console.log("number : ",number);
